AZURE_OPENAI_ENDPOINT = ""
AZURE_OPENAI_KEY = ""
AZURE_OPENAI_DEPLOYMENT = ""

AZURE_SEARCH_SERVICE = ""
AZURE_SEARCH_INDEX_NAME = ""
AZURE_SEARCH_SERVICE_KEY = ""

AZURE_BLOB_ACCOUNT = ""
AZURE_BLOB_KEY = ""
CONTAINER_NAME = ""
BLOB_CONNECTION_STRING = ""